# config.py
import warnings

warnings.filterwarnings("ignore")

DURATION_ICU_COL = "DURATION_OF_INTENSIVE_UNIT_STAY"
DURATION_STAY_COL = "DURATION_OF_STAY"

EMERGENCY_COL = "TYPE_OF_ADMISSION_EMERGENCY_OPD_E"
OPD_COL = "TYPE_OF_ADMISSION_EMERGENCY_OPD_O"

OUTCOME_COL = "OUTCOME"